server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sqlengine?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com.zzu.sqlconfig/dao/*.xml
  type-aliases-package: com.zzu.sqlconfig.entity
  configuration:
    lazy-loading-enabled: false
    lazy-load-trigger-methods: equals,clone,hashCode
    aggressive-lazy-loading: false

### log4j 配置
logging:
  config:
    classpath: log4j2.xml
